### ISSUE TITLE
Some SGE jobs remain running after cleanup()

### ISSUE THREAD

**Issue by wlandau** [mschubert/clustermq#100]
Using 6af6dff7874a1168fbe8e09dc86b9d8f41b8b1cb (`wapi` branch). Same session info as in https://github.com/mschubert/clustermq/issues/93#issue-350090566, same template file as in https://github.com/mschubert/clustermq/issues/97#issuecomment-412998074. The following completes normally but leaves an unpredictable number of SGE jobs still running even after `cleanup()` runs and the R session exits.

```r
options(clustermq.scheduler = "sge", template = "template.tmpl")
w <- clustermq::workers(8)
out <- clustermq::Q(1:2, fun = function(x) x * 2, workers = w)
w$cleanup()
```

**Comment by wlandau** [comment]
But if I call `w$finalize()` after `w$cleanup()`, those workers appear to terminate normally. With the new worker API, is it good/acceptable practice to always call `w$cleanup()` and then `w$finalize()` at the end?

**Comment by mschubert** [comment]
That's caused by workers never starting up and then they can't do the normal shutdown procedure. Needs a small patch to kill these, will fix later today.

API recommendation is still:

```r
on.exit(w$finalize())
..do event loop..
if (w$cleanup())
    on.exit()
```

**Comment by wlandau** [comment]
I thought that might be the case. After https://github.com/mschubert/clustermq/commit/ecfdb9da9870b6434f6bf689da6a3cbb94f38a2f, the API recommendation appears to clean up all the jobs correctly.
