### ISSUE TITLE
Verbosity argument for Q() and friends?

### ISSUE THREAD

**Issue by wlandau** [mschubert/clustermq#111]
Might be convenient for suppressing worker startup and shutdown messages ([example](https://github.com/mschubert/clustermq/blob/d45902f88cd47ad2bcf72f00b253dbf16085de39/R/workers.r#L26)).

**Comment by mschubert** [comment]
Do you have a use case that can not be solved by wrapping `Q(...)` in `suppressMessages`?

**Comment by wlandau** [comment]
drake has a verbosity argument that controls most of its messages. Sometimes we want messages, sometimes not. It would be slightly cleaner to pass the verbosity to Q() than to add conditional logic. Other packages with clustermq as a backend may run into similar situations.
