### ISSUE TITLE
DOCS: Drop private/protected API from help index

### ISSUE THREAD

**Issue by HenrikBengtsson** [mschubert/clustermq#113]
Consider me a clustermq rookie that is just getting into the details.  I figured it might be helpful if I share my getting-started experiences during this early phase of learning clustermq, so I'll post a few issues on whatever I find unclear or what could be improved.  These are just suggestions.  Here's one:

The HTML help index page lists lots of functions that I believe are irrelevant to most users.  It also lists help on non-exported functions, e.g. `master()`, `.onLoad()` etc.  If you use the HTML help index to get a quick overview of what's available in a package, then I find the current one to add lots of noise and it's hard to pick out what's relevant.

As a start, I'd like to suggest to use Rd `\keyword{internal}` (`@keywords internal`) for non-exported functions.  They will still be available via `?clustermq::master`.  You could also create a separate help page titled "Internal functions" where you list/link to each of those.  I think that would help identify the key players in the clustermq API.

**Comment by mschubert** [comment]
Thanks a lot @HenrikBengtsson! I've briefly looked through your comments and they are very useful. I'll start working through those.

This is fixed in `develop`.
