### ISSUE TITLE
WIKI DOCS: Some minor corrections

### ISSUE THREAD

**Issue by HenrikBengtsson** [mschubert/clustermq#115]
In https://github.com/mschubert/clustermq/wiki:

* 'batch' and 'BatchJobs' are two non-related packages: "There is also a batch package that was last updated in 2013 and superseded by BatchJobs"

* "Torque, PBS" is missing from "Schedulers: LSF, SGE, SLURM".  Are there more?

* Broken URL: "A loop of a similar structure can be used to extend clustermq. As an example, [this was done by drake](<broken URL>) using common data and custom calls only (no iterated chunks)."

* Drop "on" in: "In order to use clustermq from your local machine, the package needs to be installed [on] both there and on the computing cluster."

**Comment by mschubert** [comment]
> 'batch' and 'BatchJobs' are two non-related packages: "There is also a batch package that was last updated in 2013 and superseded by BatchJobs"

Yep, that's wrong. Fixed.

> "Torque, PBS" is missing from "Schedulers: LSF, SGE, SLURM". Are there more?

Fixed. These are the currently supported 5.

Also added OpenLava & Docker Swarm for `batchtools`.

> Broken URL: "A loop of a similar structure can be used to extend clustermq. As an example, this was done by drake using common data and custom calls only (no iterated chunks)."

Fixed.

> Drop "on" in: "In order to use clustermq from your local machine, the package needs to be installed [on] both there and on the computing cluster."

Fixed.
