### ISSUE TITLE
WIKI DOCS: Outdated information about PBS

### ISSUE THREAD

**Issue by HenrikBengtsson** [mschubert/clustermq#117]
https://github.com/mschubert/clustermq/wiki/PBS mentions `cores` which should be `n_jobs`;

```
#PBS -N {{ job_name }}
#PBS -l select=1:ncpus={{ cores | 1 }}
#PBS -l walltime={{ walltime | 1:00:00 }}
#PBS -q default
#PBS -o {{ log_file | /dev/null }}
#PBS -j oe

ulimit -v $(( 1024 * {{ memory | 4096 }} ))
R --no-save --no-restore -e 'clustermq:::worker("{{ master }}")'
```

**Comment by mschubert** [comment]
`cores` is correct (but not required, the other templates don't list the number of cores per job), but `n_jobs` should be listed as:

```
#PBS -l nodes={{ n_jobs }}:ppn=1
```

Fixed.

**Comment by HenrikBengtsson** [comment]
I see.   So, to be 100% sure I'm on the same page, you did indeed mean:
```r
#PBS -l nodes={{ n_jobs }}:ppn=1
```
and not
```r
#PBS -l nodes=1:ppn={{ n_jobs }}
```
correct?  ...because ZeroMQ allows you to distribute across hosts while still working on a single host if the scheduler chooses to.

**Comment by mschubert** [comment]
Err, yes, copy & paste error. Good catch!

**Comment by mschubert** [comment]
Actually, I'm no longer sure.

```
#PBS -l nodes={{ n_jobs }}:ppn=1
```

would request `n_jobs` nodes with one processor and

```
#PBS -l nodes=1:ppn={{ n_jobs }}
```

would request 1 node with `n_jobs` processors.

Depends how this is implemented in PBS, which I don't know. And I don't think we've had any PBS users yet that could have reported on this.

**Comment by mschubert** [comment]
I have now merged `n_jobs` and `cores` into one line that I think (according to the documentation is correct):

```r
#PBS -l nodes={{ n_jobs }}:ppn={{ cores | 1 }}
```
