### ISSUE TITLE
Workers keep running if the master is a callr process and terminates early.

### ISSUE THREAD

**Issue by wlandau** [mschubert/clustermq#130]
Ordinarily, `clustermq` [automatically terminates workers if the master terminates](https://github.com/mschubert/clustermq/blob/371082c2595ec32ebecbde0c7501ec0e0229c2b5/R/master.r#L34), which is extremely helpful. However, if the master is a [`callr`](https://github.com/r-lib/callr) process, then workers keep running even after SIGINT. Example:

```
callr::r(function() clustermq::Q(Sys.sleep, 60, n_jobs = 1))
```

After I terminate this call early with CTRL-C, the worker stays up on SGE.

Related: https://github.com/ropensci/drake/issues/772. cc @pat-s.

**Comment by mschubert** [comment]
This seems to be related to `callr` rather than `clustermq`:

```r
> callr::r(function() { on.exit(system("echo here > ~/test.out")); Sys.sleep(0) })
> callr::r(function() { on.exit(system("echo here2 > ~/test2.out")); Sys.sleep(60) }) ^C
```

```bash
$ cat test.out
here
$ cat test2.out
cat: test2.out: No such file or directory
```

Nothing I can do about that.
