### ISSUE TITLE
parallel glmnet requires `.packages` in `foreach`

### ISSUE THREAD

**Issue by Zhuk66** [mschubert/clustermq#140]
The following code does not work:
> library(glmnet)
> set.seed(1010)
> n=1000;p=100
> nzc=trunc(p/10)
> x=matrix(rnorm(n*p),n,p)
> beta=rnorm(nzc)
> fx= x[,seq(nzc)] %*% beta
> eps=rnorm(n)*5
> y=drop(fx+eps)
> px=exp(fx)
> px=px/(1+px)
> ly=rbinom(n=length(px),prob=px,size=1)
> set.seed(1011)
> cvob1=cv.glmnet(x,y, parallel=T)
Error in e$fun(obj, substitute(ex), parent.frame(), e$data) :
  foreach .packages currently not supported in clustermq
5: (function ()
   traceback(2))()
4: stop("foreach .packages currently not supported in clustermq")
3: e$fun(obj, substitute(ex), parent.frame(), e$data)
2: foreach(i = seq(nfolds), .packages = c("glmnet")) %dopar% {
       which = foldid == i
    ...
1: cv.glmnet(x, y, parallel = T)
>

cv.glmnet calls foreach with .packages that is not currently supported. Can you add support for .packages?

**Comment by mschubert** [comment]
Yes, that's on the list and I'll add it in the next release.

Thank you for documenting this.

**Comment by mschubert** [comment]
@Zhuk66 This should be fixed in the latest `develop`, it would be great if you could test it

**Comment by Zhuk66** [comment]
Thank you very much. I will.
