### ISSUE TITLE
`scancel --jobname` is not supported by older versions of SLURM

### ISSUE THREAD

**Issue by ashiklom** [mschubert/clustermq#148]
Our HPC is stuck on a pretty old version of SLURM (14.03), for which `scancel --jobname` doesn't exist -- only `scancel --name` (which does the same thing). Here is the [man page](https://slurm.schedmd.com/archive/slurm-14.11-latest/scancel.html) for `scancel` v.14.11.

In the current version of SLURM (19.05, as of this issue), `scancel --jobname` is a synonym for `scancel --name` ([man page](https://slurm.schedmd.com/scancel.html)), presumably for backwards-compatibility.

Given that HPCs are often pretty conservative about updating core systems like this, it would be nice if `clustermq` supported older versions of SLURM. The easiest would be just to change the call from `--jobname` to `--name` in the [`SLURM::finalize` method](https://github.com/mschubert/clustermq/blob/371082c2595ec32ebecbde0c7501ec0e0229c2b5/R/qsys_slurm.r#L28).

**Comment by mschubert** [comment]
That makes a lot of sense, thanks!

Can you send a PR?

**Comment by mschubert** [comment]
Merged, thanks!
