### ISSUE TITLE
Reuse common data

### ISSUE THREAD

**Issue by mschubert** [mschubert/clustermq#154]
If I set up workers with multiple subsequent computations, it would be nice to only re-send constant/exported data if it actually changes.

Something like:

```
Running 21,010 calculations (5 objs/348.8 Mb common - 56% reuse; 11 calls/chunk) ...
```

Could potentially store this for more computations as well, but that will get tricky with memory management (if we're reaching the limit, we'd want to delete unused objects rather than failing the computation - but how to track this?)

**Comment by wlandau** [comment]
Awesome! Seems like data reusage could power #147 and https://github.com/ropensci/drake/issues/672 quite nicely.
