### ISSUE TITLE
Consider high water mark for sending messages

### ISSUE THREAD

**Issue by mschubert** [mschubert/clustermq#161]
From https://github.com/ropensci/drake/issues/933#issuecomment-510464039:

> The problem is that all of these transfers are being started concurrently. If `Qsys$private$send()` blocked execution until the transfer was complete, then the memory requirements would be limited to the dependencies for one target. However, the current situation is that `Qsys$private$send()` returns as soon as the transfer is scheduled (because `rzmq::send.socket()` returns as soon as the transfer is scheduled), and so `drake` schedules the next target, which means filling the buffer for the next transfer before the first has finished. The result is that dependencies for many targets (whether they are the same data or not) are buffered on the master at the same time.

This could be addressed using [ZMQ_HWM](http://api.zeromq.org/2-1:zmq-setsockopt#toc3).

Alternative is using blocked sending: https://github.com/ropensci/drake/issues/933#issuecomment-510371511

> It looks like pbdZMQ [uses blocking connections by default](https://github.com/RBigData/pbdZMQ/blob/fa49d1aa024e39b9caad67ad7fdbd1552d408d33/R/R_zmq_sendrecv.r#L92). This is also the behavior of the [rzmq-compatibility wrapper function](https://github.com/RBigData/pbdZMQ/blob/fa49d1aa024e39b9caad67ad7fdbd1552d408d33/R/rzmq_wrapper.r#L59-L66), so blocking will come along for the ride by default if clustermq switches to using pbdZMQ.

**Comment by wlandau** [comment]
Do you plan to expose the high water mark? Some workflows are not memory intensive and could still benefit from the existing non-blocking behavior.

**Comment by mschubert** [comment]
I wasn't planning on to, but will have to investigate how ZeroMQ treats this exactly with its IO threads.

Generally, I wouldn't expect this to be an issue because we're blocking on receiving anyway, and the workers will be saturated in either case.

If there's a problem with that approach that needs user/package intervention I will expose it, otherwise not.

**Comment by mschubert** [comment]
@brendanf This may be already fixed in the [`v0.9` branch](https://github.com/mschubert/clustermq/tree/v0.9), please test if you have the time
