### ISSUE TITLE
clustermq not work for foreach %dopar% in drake

### ISSUE THREAD

**Issue by kongdd** [mschubert/clustermq#162]
```r
library(foreach)
library(clustermq)
library(drake)
# clean()
register_dopar_cmq(n_jobs=2, memory=1024)
options(clustermq.scheduler = "multicore")

plan <- drake_plan(
    x = foreach(i=1:3) %dopar% sqrt(i))
# vis_drake_graph(drake_config(plan))
make(plan, parallelism = "clustermq", jobs = 2)
# loadd(x); print(x)
```
Then rstudio is stucked.

**Comment by wlandau** [comment]
`make(parallelism = "clustermq")` is for parallelism *among* targets. It looks like you want to use `clustermq` *within* a target instead. How about this?

```r
library(foreach)
library(clustermq)
library(drake)

plan <- drake_plan(
  x = {
    register_dopar_cmq(n_jobs=2, memory=1024)
    options(clustermq.scheduler = "multicore")
    foreach(i=1:3) %dopar% sqrt(i)
  }
)

make(plan)
```

**Comment by wlandau** [comment]
Sorry, https://github.com/mschubert/clustermq/issues/162#issuecomment-510976461 is not actually  the problem. I reproduced your error in both https://github.com/mschubert/clustermq/issues/162#issue-467502135 and https://github.com/mschubert/clustermq/issues/162#issuecomment-510976461. Both worked for me when I set `lock_envir = FALSE` in `make()`. Details: https://ropensci.github.io/drake/reference/make.html#self-invalidation.

``` r
library(foreach)
library(clustermq)
#> * Option 'clustermq.scheduler' not set, defaulting to 'LOCAL'
#> --- see: https://mschubert.github.io/clustermq/articles/userguide.html#configuration
library(drake)

register_dopar_cmq(n_jobs=2, memory=1024)
options(clustermq.scheduler = "multicore")

plan <- drake_plan(
  x = foreach(i=1:3) %dopar% sqrt(i))

make(plan, parallelism = "clustermq", jobs = 2, lock_envir = FALSE)
#> target x
#> Target x messages:
#>   Submitting 2 worker jobs (ID: 7289) ...
#>   Running 3 calculations (1 objs/0 Mb common; 1 calls/chunk) ...
#>   Master: [0.2s 41.1% CPU]; Worker: [avg 20.2% CPU, max 3671562.0 Mb]
#> Master: [0.5s 14.5% CPU]; Worker: [avg 52.8% CPU, max 3671562.0 Mb]

readd(x)
#> [[1]]
#> [1] 1
#> 
#> [[2]]
#> [1] 1.414214
#> 
#> [[3]]
#> [1] 1.732051
```

<sup>Created on 2019-07-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

With that, I vote to close.

**Comment by mschubert** [comment]
Hi @kongdd,

Thank you for your interest in the package!

It looks like your problem is more related to `drake` than `clustermq`, and @wlandau linked the documentation of why this happens. So there is not really anything `clustermq` can do differently here.

@wlandau Shouldn't this produce an error instead of getting stuck?

**Comment by wlandau** [comment]
Running in a locked environment outside `drake` produces an error message.

```r
> library(clustermq)
* Option 'clustermq.scheduler' not set, defaulting to ‘LOCAL’
--- see: https://mschubert.github.io/clustermq/articles/userguide.html#configuration
> library(foreach)
> options(clustermq.scheduler = "multicore")
> register_dopar_cmq(n_jobs = 2, memory = 1024)
> drake:::lock_environment(globalenv())
> foreach(i = 1:3) %dopar% sqrt(i)
Error in sample.int(length(x), size, replace, prob) : 
  cannot add bindings to a locked environment
```

`drake` already does try to catch this error and throws a more informative message.

- https://github.com/ropensci/drake/blob/da7d2abc5e1c3486c33197afaf285eaf31af733a/R/exec-run.R#L67
- https://github.com/ropensci/drake/blob/da7d2abc5e1c3486c33197afaf285eaf31af733a/R/utils-handlers.R#L69-L82

I am not sure why it is not working in this particular case.

**Comment by mschubert** [comment]
There have also been some reports of issues with multicore in RStudio: https://github.com/HenrikBengtsson/future/issues/299

I'd be interested to see if the same problem (stuck instead of error) happens on a multiprocess backend (https://github.com/mschubert/clustermq/issues/142) but I haven't implemented that yet.

**Comment by wlandau** [comment]
True. This particular foreach issue seems to persist in R outside Rstudio, though. And in both cases, drake successfully handles the inevitable clash with mclapply().

**Comment by kongdd** [comment]
Thanks @wlandau and @mschubert
