### ISSUE TITLE
callr backend

### ISSUE THREAD

**Issue by wlandau** [mschubert/clustermq#173]
I like how `callr` avoids sockets and ports, and I find it to be more robust than `parallel` overall. I think `options(clustermq.scheduler = "callr")` could be really useful. Related: #64 and #142.

**Comment by mschubert** [comment]
I thought about this. - The reason to not use `callr` is because of the added external dependencies.

Avoiding sockets for the R processes is not really an advantage, because we (currently) need sockets for `rzmq` anyway.

However, I see that this may be useful. I'll keep it open as enhancement.

**Comment by mschubert** [comment]
Actually closing this, tracked in #142
