### ISSUE TITLE
Conflicting information about usage of PBS/Torque Schedulers

### ISSUE THREAD

**Issue by mstr3336** [mschubert/clustermq#184]
According to the [README](https://github.com/mschubert/clustermq/blob/master/README.md#schedulers), using a PBS scheduler requires setting `options(clustermq.scheduler="PBS"/"Torque")`, however according to [this doc](https://github.com/mschubert/clustermq/blob/master/README.md#schedulers), we should specify the following:

```r
options(
    clustermq.scheduler = "sge",
    clustermq.template.lsf = "/path/to/file/below"
)
```

I'm confused about which is true, or whether it matters

Cheers!

**Comment by mstr3336** [comment]
For now, I'm using 

```r
options(
  clustermq.scheduler="PBS",
  clustermq.template.lsf = "/path/to/file/below"
```

Template:

```

#!/bin/bash


#PBS -N {{ job_name }}
#PBS -l select=1:ncpus={{ ncpus | 1 }}:mem={{ mem | 2GB }}
#PBS -l walltime={{ walltime | 1:00:00 }}
#PBS -q defaultQ
#PBS -o {{ log_file | /dev/null }}
#PBS -j oe

## Project name
#PBS -P STEMI

## Email on abort (a) and termination (e), but not when starting (b)
## Requires mailutils if on Linux.
#PBS -m ae
# #PBS -M matthew.strasiotto+stemi@gmail.com

module load R/3.5.2
module load zeromq

cd {{ workdir | "$PBS_O_WORKDIR" }}

ulimit -v {{ memory | 2097152 }}
CMQ_AUTH={{ auth }} R --no-save --no-restore -e 'clustermq:::worker("{{ master }}")'

```

The errors that I tend to get are as follows:

```
.qsub: The project has not been supplied. Please specify project with '-P <project>' or #PBS -P <project> in the job script.
[1] "#PBS -N cmq7470\n#PBS -l nodes=24:ppn=1\n#PBS -o /project/STEMI//logs/cmq_worker.log\n#PBS -j oe\n\nulimit -v $(( 1024 * 2097152 ))\nCMQ_AUTH=qloem R --no-save --no-restore -e 'clustermq:::worker(\"tcp://hpc001:7470\")'\n"
Error in (function (...)  : Job submission failed with error code 32
Error in (function (...)  : Job submission failed with error code 32
Calls: <Anonymous> -> r_drake -> do.call -> <Anonymous> -> get_result
Execution halted

```

For readability, I'll split up the `\n`s in the above:

```
"
#PBS -N cmq7470
#PBS -l nodes=24:ppn=1
#PBS -o /project/STEMI//logs/cmq_worker.log
#PBS -j oe

ulimit -v $(( 1024 * 2097152 ))
CMQ_AUTH=qloem R --no-save --no-restore -e 'clustermq:::worker(\"tcp://hpc001:7470\")'
"

```

And the `template` argument I'm passing to `drake::config` :

```r
list(
    select = 1,
    ncpus  = 1,
    mem    = "2gb",
    # set memory 2GBytes, to pass to ulimit -v {{ memory }} which accepts
    # a value in kilobytes
    memory = 2*(1024^2), 
    workdir = here::here(),
    #walltime = "23:59:59" # Persistent workers might want more walltime
    walltime = "1:00:00",
    log_file = root$join("logs")$join("cmq_worker.log")$show
  )
```

This is doing my head in, what am I missing? 

It seems like the templating system is doing some works behind the schenes on what I've provided it, but I'm really struggling to understand what it is that I'm looking at and why it's producing this output. 

My workplace has a customized PBS Pro system that requires a few nonstandard parameters, in particular the `-P <project_name>` specification. 

Why am I not seeing this in the output?

**Comment by mstr3336** [comment]
Having reviewed the source for the various QSys classes, I think I see what's happening to an extent.

https://github.com/mschubert/clustermq/blob/master/R/qsys_sge.r#L40-L48

Am I right in thinking that the documentation specifying we set :

```r
options(
   clustermq.template.lsf = "path"
)
```

is out of date, and I should be setting 

```r
options(
   clustermq.template = "path"
)
``` 

instead?

**Comment by mstr3336** [comment]
also, setting a scheduler that derives from SGE just provides default values for the template file if a template isn't specified

**Comment by mstr3336** [comment]
In my opinion, a lot of this behaviour is non-obvious from the package's usage section, and from the output messages produced by `clustermq` . 

I think I might have been saved a fair few hours of pain with an informative message indicating that a default template is going to be used.

**Comment by mstr3336** [comment]
# Update / Answer

Yes, ignoring both the [usage](https://mschubert.github.io/clustermq/articles/userguide.html#PBS) & the [README](https://github.com/mschubert/clustermq#schedulers) finally allowed successful submission to my scheduler.

In particular, the change that made this work was as follows:

Ignore [usage](https://mschubert.github.io/clustermq/articles/userguide.html#PBS)'s recommendation to set `option(clustermq.template.lsf = "path")`, and instead set `option(clustermq.template = "path")`. 

I assume the `.lsf` suffix is a typo in the docs/outdated. 

The result of this being unset was for `clustermq` to silently default to a PBS template if `options(clustermq.scheduler = "PBS")` is set, or to an SGE template if `options(clustermq.scheduler = "sge") is set. 


Do note that there *are* problems with the template I provided, which I'll describe, but the above observations are still valid. 

I shouldn't be passing `ncpus` to drake's template arg, and then filling it in the template, instead I should use the `cores` field (Like I was told to in the first place).

**Comment by mstr3336** [comment]
Just to provide a **tl;dr** on this:

- The [usage](https://mschubert.github.io/clustermq/articles/userguide.html#PBS) and [readme](https://github.com/mschubert/clustermq#schedulers) provide conflicting information on using PBS based schedulers
- The options given in the usage are wrong
  - They specify setting `clustermq.template.lsf` instead of just `clustermq.template`
https://github.com/mschubert/clustermq/blob/133f4e47fd74dfd61e57de26774b2131fb219cf2/vignettes/userguide.Rmd#L537-L542
  - This will cause `clustermq` to silently fail to find an option for `clustermq.template`, and use the default `sge` template. 
- The template given in the usage is wrong, assuming the user would like to submit their job to more than one worker.
  https://github.com/mschubert/clustermq/blob/133f4e47fd74dfd61e57de26774b2131fb219cf2/vignettes/userguide.Rmd#L548-L556
- The default template given according to following the [readme](https://github.com/mschubert/clustermq#schedulers) and setting `options(clustermq.scheduler = "PBS")` is wrong - Or at least doesn't work on my system. 
  https://github.com/mschubert/clustermq/blob/133f4e47fd74dfd61e57de26774b2131fb219cf2/inst/PBS.tmpl#L1-L7

  - Contrast with the SGE template
   https://github.com/mschubert/clustermq/blob/133f4e47fd74dfd61e57de26774b2131fb219cf2/inst/SGE.tmpl#L6-L7

  - Notice that the SGE template submits a job array of `n_jobs`, but with only `cores` per job
- This is true of some of the other templates:
  https://github.com/mschubert/clustermq/blob/133f4e47fd74dfd61e57de26774b2131fb219cf2/inst/SLURM.tmpl#L6-L7

   https://github.com/mschubert/clustermq/blob/133f4e47fd74dfd61e57de26774b2131fb219cf2/inst/LSF.tmpl#L1-L2

- The correct PBS template should resemble the following
  ```bash
  #PBS -N {{ job_name }}
  # Submit a job array of n jobs
  #PBS -J 1-{{ n_jobs }}
  # I'm not sure if "mem" is a standard PBS parameter, or is specific to our cluster
  # "mem" is the only part I'm less certain of
  # Request one chunk per job, with "cores" per chunk, and "mem" memory per chunk
  #PBS -l select=1:ncpus={{ cores | 1 }}:mpiprocs={{ cores | 1 }}:mem={{ mem | 2GB }}
  #PBS -l walltime={{ walltime | 1:00:00 }}

  #PBS -o {{ log_file | /dev/null }}
  #PBS -j oe

  ulimit -v {{ memory | 2097152 }}
  CMQ_AUTH={{ auth }} R --no-save --no-restore -e 'clustermq:::worker("{{ master }}")'
  ```
  Jobs submitted in this way will actually distribute work in parallel

**Comment by mstr3336** [comment]
@mschubert since you've labeled this a bug, I'm going to go ahead and put in a PR to fix it

**Comment by mstr3336** [comment]
@mschubert when you have time, could you please review #185 ? It should resolve this

**Comment by mschubert** [comment]
Hi @mstr3336,

Thank you for spotting this and also providing the PR.

> also, setting a scheduler that derives from SGE just provides default values for the template file if a template isn't specified

 This is expected behavior, but I agree it should be mentioned more explicitly in the documentation (README, User Guide)

> since you've labeled this a bug, I'm going to go ahead and put in a PR to fix it

> They specify setting clustermq.template.lsf instead of just clustermq.template

Thanks! The "bug" part here is the incorrect documentation (left over from a previous version), and potentially a wrong PBS template (see below).

> The template given in the usage is wrong, assuming the user would like to submit their job to more than one worker

> The default template given according to following the readme and setting options(clustermq.scheduler = "PBS") is wrong - Or at least doesn't work on my system

I remember putting together the template according to PBS documentation that I found online. This may have been severely out of date, and I've got no way to test this (I only have access to LSF and Slurm).

If I'm changing this, I want to make sure that there are not just multiple flavors of PBS with different options. Do you know if PBS Pro is the only PBS scheduler available? (You may be our first PBS user, I've never actually interacted with this scheduler before.)
