### ISSUE TITLE
User-specified worker timeouts

### ISSUE THREAD

**Issue by wlandau** [mschubert/clustermq#188]
I have received several reports of `drake` users encountering worker timeouts, most notably https://github.com/ropensci/drake/issues/1146, https://github.com/ropensci/drake/issues/1148, and https://github.com/ropensci/drake/issues/1150. They all seem related to the default timeout of `worker()`.

https://github.com/mschubert/clustermq/blob/9ba37a3cd17d82e39fda8133a4e1cd36cc76b50d/R/worker.r#L10

What if users could set their own worker timeouts? Is this already possible in the template? If not, I am open to building a `clustermq_worker_timeout` argument into `drake::make()`, but it would require analogous functionality in `clustermq::workers()`.

cc @jennysjaarda, @mike-lawrence.

**Comment by mschubert** [comment]
I see your point.

Timeouts should go away in `0.9` and be replaced by monitoring worker sockets for disconnects (https://github.com/mschubert/clustermq/projects/5).

If that release gets delayed much longer (because of my time constraints) I'll release a `0.8.9` that includes this option.

**Comment by wlandau** [comment]
Fantastic, thanks!
