### ISSUE TITLE
Calling qsub from inside a singularity container

### ISSUE THREAD

**Issue by PhDyellow** [mschubert/clustermq#193]
Covering an issue that is explicitly avoided in #192.

When using PSBPro, and probably other backends that submits jobs to a HPC scheduler, the `qsub` command is used to submit the jobs. When R is installed on the nodes as a module or regular program on the path, it works because `qsub` is on the path.

However, Singularity containers are partially isolated from the host by design, and can have different c library stacks to the host. Bringing `qsub` into the container is hard, and breaks the portability of the container.

I'm not sure if clustermq can do anything about this. The end result is that if R is inside a container, then qsub is not available, and clustermq cannot start up the workers.

**Comment by PhDyellow** [comment]
I ended up finding a workaround, inspired by the ssh backend, which might be useful to others. 

Create a bash script named `qsub` with the following contents:

```
#!/bin/sh
ssh -i /home/PhDyellow/.ssh/selfkey ${PBS_O_HOST:-"no_host_not_in_a_pbs_job"} qsub "$@"
```

Put it on the path inside the container. Now `qsub` exists, contacts the HPC host via SSH, and submits the job. By default, containers share networking with their node, so the workers can connect to the master process when they spin up.

The ssh key does need to be password-less, which seems like a security risk. Create a new key that serves no other purpose, make sure the key owner is not an administrator, and in the `.ssh/authorized_keys` file, set the `from="*.local"` option to only allow logins from within the HPC cluster. I'm not a security expert though, any suggestions are welcome.

**Comment by mschubert** [comment]
Thanks, that's a possible solution and should probably go in the [User Guide#Environments](https://mschubert.github.io/clustermq/articles/userguide.html#environments). If you want to give it a stab for a PR I'd be happy to merge, otherwise I'll do it for the next release.

Alternatively, copying (linking?) the scheduler executable (and libs?) to the home directory also [seems to work](https://groups.google.com/a/lbl.gov/d/msg/singularity/syLcsIWWzdo/NZvF2Ud2AAAJ).

**Comment by wds15** [comment]
Not sure where to place this...but I had the issue of having to log into my cluster via ssh where R is only available upon loading a specific module to make the R version available. It took me almost a day to figure out what to do:

The key step was to come up with this modified SSH template:

```
ssh -o "ExitOnForwardFailure yes" -f \
    -R {{ ctl_port }}:localhost:{{ local_port }} \
    -R {{ job_port }}:localhost:{{ fwd_port }} \
    {{ ssh_host }} \
    "source /etc/profile; module load R-bundle; /absolute/path/to/bin/R --no-save --no-restore -e \
        'clustermq:::ssh_proxy(ctl={{ ctl_port }}, job={{ job_port }})' \
        > {{ ssh_log | /dev/null }} 2>&1"

```

Note the sourcing of /etc/profile and use of the absolute path to R. Maybe this is worth including in the doc? Sorry if this is off topic here, but this issue got me on track (or at least I came across it).
