### ISSUE TITLE
Warnings aren’t propagated to caller

### ISSUE THREAD

**Issue by klmr** [mschubert/clustermq#21]
I’m using clustermq to download large files via the R function `utils::download.files`. Unfortunately, that function reports presumably failed downloads as a warning. As this warning isn’t propagated to the caller, there’s no indication that downloads failed.

In addition, this happens extremely commonly — more commonly than I’d usually expect. I am not sure whether this is due to a quota limitation (though I cannot find any such quota on the website in question — ArrayExpress) or something to do with clustermq.

Here’s some code to reproduce the problem:

```r
library(dplyr)

uri = 'https://www.ebi.ac.uk/arrayexpress/files/E-MTAB-2328/E-MTAB-2328.sdrf.txt'
samples = readr::read_tsv(uri) %>%
    select(Uri = `Comment[FASTQ_URI]`) %>%
    mutate(File = basename(Uri))

clustermq::Q(download.file, url = samples$Uri, destfile = sample$File,
             memory = 500, job_size = 1, log_worker = TRUE) %>% invisible()
```

This will download the (48) files without indicating an error. However, some of these files will be truncated. The `rzmq*.log` will contain something like the following lines:

```bash
⟩⟩⟩ grep -A2 'Warning message:' rzmq*.log
rzmq7111-46.log:Warning message:
rzmq7111-46.log-In (function (url, destfile, method, quiet = FALSE, mode = "w",  :
rzmq7111-46.log-  downloaded length 0 != reported length 2034745308
```

**Comment by mschubert** [comment]
Yes, we should find some way to display warnings of function calls back on the master.

For the timeout itself, have you tried running from bash in parallel and see if the error occurs then as well?

**Comment by klmr** [comment]
Actually it does … seems ArrayExpress is dropping my connections beyond some threshold. I’ll contact support to find out why.

**Comment by mschubert** [comment]
@klmr I tried to [implement this](https://github.com/mschubert/clustermq/blob/develop/R/worker.r#L75), but I'm not quite sure why it doesn't pass warnings that occur.

Even if I add a `warning("test")` on [L#68](https://github.com/mschubert/clustermq/blob/develop/R/worker.r#L68) nothing gets passed back to the master.

Any idea?

**Comment by klmr** [comment]
See my review.

**Comment by mschubert** [comment]
Testing code for using `withCallingHandlers`:

```r
fx = function(a, ...) {
    if (a %% 3 == 0)
        warning("this is a warning")
    if (a %% 2 == 0)
        stop("this is an error")
    a
}

fwrap = function(...) {
    context = new.env()

    context$result = withCallingHandlers(fx(...),
        warning = function(w) {
            context$warnings = c(context$warnings,
                                 list(as.character(conditionMessage(w))))
            invokeRestart("muffleWarning")
        },
        error = function(e) {
            context$error = as.character(conditionMessage(e))
            NULL
        }
    )

    as.list(context)
}

fwrap(a=1)
fwrap(a=3)
fwrap(a=2)
fwrap(a=6)
```

**Comment by klmr** [comment]
Now you just need to add `withVisible` (and `message`). ;-)

**Comment by mschubert** [comment]
Not really. The `worker` is not concerned with the calls it evaluates, just the framework it provides.

The `master`, on the other hand, is now reporting warnings and errors :smiling_imp:
