### ISSUE TITLE
Cannot allocate buffer when running HPC jobs in singularity container

### ISSUE THREAD

**Issue by mattwarkentin** [mschubert/clustermq#224]
Hi @mschubert,

I'm getting an error that I'm not convinced is `clustermq`s fault, but I was wondering if you have any thoughts/insight into this error and what it might be indicating?
```
Error in private$zmq$send(data, sid, dont_wait, send_more) : 
  Evaluation error: cannot allocate buffer.
Calls: <Anonymous> -> <Anonymous> -> <Anonymous> -> .External
Execution halted
```
I don't really know how to work backward and figure out what is throwing this error.

For context, this is running on HPC using Slurm as the scheduler, and the worker processes are running inside singularity containers.

**Comment by mschubert** [comment]
Failed memory allocations are usually OOM. Do you maybe have some limits set on the container that you're hitting?

**Comment by mattwarkentin** [comment]
I'm working through various debugging techniques. I will close this for now and come back if I have anything more useful to share.
