### ISSUE TITLE
What are the causes of private$zmq$poll(sid, timeout) : 1 peer(s) lost

### ISSUE THREAD

**Issue by liutiming** [mschubert/clustermq#228]
referring to #212 , I often have this error message. Sometimes jobs are completed (submitted using targets) and sometimes the job cannot be submitted at all. I am wondering what causes this error?

**Comment by mschubert** [comment]
Please see https://github.com/mschubert/clustermq/issues/223, and use the release version (e.g. via `install.packages("clustermq")`) to avoid this bug
