### ISSUE TITLE
passing run time to bsub (-W)

### ISSUE THREAD

**Issue by gabora** [mschubert/clustermq#25]
Hi,
could you please include an interface to runtime (#BSUB-W <runtime>)? 
either through options
  options(clustermq.runtime = ?)
or maybe through the Q function?

this way, we could overwrite the default 15 mins on our cluster. 
thanks!

**Comment by mschubert** [comment]
I added this now in `develop`:https://github.com/mschubert/clustermq/commit/2e2b109090039d3701dd5ac0abc0cf83eba6ef8d

For more information to use it, see: https://github.com/mschubert/clustermq/wiki/LSF

All the tests still pass, but I haven't actually checked if it works as expected. I'll leave that to you.

**Comment by gabora** [comment]
Hi,
thanks!
It raises some errors: argument walltime not used. 
It seems, that you changed only the  qsys$submit_jobs() interface in the superclass, but not the interfaces of the inherited classes: qsys_lsf or qsys_ssh. 
I forked the repo and I am  trying to fix it:)

**Comment by mschubert** [comment]
Please note that the `walltime` argument is deprecated and will be removed in [`0.6.0`](https://github.com/mschubert/clustermq/tree/0.6.0).

Instead, you can supply arbitrary template functions via `scheduler_args` (https://github.com/mschubert/clustermq/issues/28).
