### ISSUE TITLE
(develop) torque/PBS- In worker cleanup, seems to be sending job names instead of PBS ids (Apparent regression of #186)

### ISSUE THREAD

**Issue by strazto** [mschubert/clustermq#265]
This appears to be a regression of #186 in the develop branch. Not sure what's changed

```r
qdel: illegally formed job identifier: cmq7547
```

**Comment by matthewstrasiotto** [comment]
Maybe #187 never properly fixed it? From what I can see, not much has changed

**Comment by mschubert** [comment]
Wasn't this your PR? :smile:

**Comment by matthewstrasiotto** [comment]
> Wasn't this your PR? 😄

Yep! 
I swear it worked at the time, but somehow, for a reason that isn't clear to me, the job-name is being used for qdel instead of the id. 

It could be a bug from some other change that somehow changed which QSys subclass is instantiated, but I haven't fully delved into it yet

**Comment by mschubert** [comment]
I think I fixed this now, if not please reopen
