### ISSUE TITLE
Expected PROXY_READY, recieve 'PROXY_ERROR: no file found'

### ISSUE THREAD

**Issue by Aariq** [mschubert/clustermq#267]
I've followed the setup guide and successfully used `clustermq` logged into the cluster, but now I'm trying to run it via SSH and I'm getting the following error:

``` r
library(clustermq)
#> * Option 'clustermq.scheduler' not set, defaulting to 'LOCAL'
#> --- see: https://mschubert.github.io/clustermq/articles/userguide.html#configuration
options(
  clustermq.scheduler = "ssh",
  clustermq.ssh.host = "<redacted@redacted.edu>, # use your user and host
  clustermq.ssh.log = "~/cmq_ssh.log" # log for easier debugging
)
fx = function(x) x * 2
Q(fx, x=1:3, n_jobs=1)
#> Connecting <redacted@redacted.edu> via SSH ...
#> Sending common data ...
#> Error in .subset2(public_bind_env, "initialize")(...): Expected PROXY_READY, received 'PROXY_ERROR: no file found'
```

<sup>Created on 2021-06-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I've got a SLURM template file on the cluster at `~/slurm_clustermq.tmpl` and I've added the following to `~/.Rprofile` on the cluster:
```r
options(
  clustermq.scheduler = "slurm",
  cluster.template = "~/slurm_clustermq.tmpl"
)
```

**Comment by mschubert** [comment]
Just to confirm, does your call work when you run it directly on the cluster? Can you post the output?

(because your error likely says that the remote process does not find its template file, which should show up there as well)

**Comment by Aariq** [comment]
Ah, you're right, the template wasn't being found. I had a typo in my template file name 🤦🏻‍♂️.  Thanks!
