### ISSUE TITLE
clustermq was removed from CRAN?

### ISSUE THREAD

**Issue by luwidmer** [mschubert/clustermq#317]
Apparently clustermq was removed from CRAN - see https://cran.r-project.org/web/packages/clustermq/ ? I saw 0.9.1 was submitted on cransays at some point, but now it seems to be gone @mschubert ?

**Comment by mschubert** [comment]
Yes, I'm aware and submitted a fix a week ago. The CRAN Team didn't want to accept `0.9.1` because it didn't use the already installed _libzmq_, regardless of it missing the _DRAFT_ API.

I've contacted them to resolve this, and hopefully `0.9.1` will be up soon!

**Comment by luwidmer** [comment]
Fingers crossed!

**Comment by mschubert** [comment]
We're back since Tuesday!
