### ISSUE TITLE
clustermq 0.9.3 worker stats NA?

### ISSUE THREAD

**Issue by luwidmer** [mschubert/clustermq#325]
First of all, thanks a lot for the massive drop of bugfixes since version 0.9.0, @mschubert!
With version 0.9.3, I so far only encountered the issue that worker stats are NA / 0:
![image](https://github.com/mschubert/clustermq/assets/9111830/daa2a342-7b33-41e7-9fd7-ecc5213d035b)

Could it be that in https://github.com/mschubert/clustermq/blob/c692d59c29672d45ec8840bae6f473ffd6aaa076/R/pool.r#L107
the info 

```r
info = self$info()
```

should be retrieved before these lines are executed?

```r
success = private$master$close(as.integer(timeout*1000))
success = self$workers$cleanup(success, timeout) # timeout left?
```

**Comment by luwidmer** [comment]
Just tried patching this and recompiling the package, that seems to fix the issue:
![image](https://github.com/mschubert/clustermq/assets/9111830/8feb80bc-358e-44bb-83fb-ab093ca83a10)

**Comment by mschubert** [comment]
Nooo I remember I wanted to fix this before the release and then I forgot about it :sweat: 

Thanks for reporting!

**Comment by luwidmer** [comment]
Any chance of getting a clustermq 0.9.3.1 / 0.9.4 :) ?
