### ISSUE TITLE
Error in qsys$cleanup() : argument "success" is missing, with no default

### ISSUE THREAD

**Issue by weizhu365** [mschubert/clustermq#326]
Dear Developers;

I ran clustermq with the scheduler "SSH" and launch the slurm cluster in the remote server, and the returned results are all right.  
Q(fx, x = 1:3, n_jobs = 3, log_worker = T)
Connecting to ‘zhuw10@cn4337’ via SSH ...
Running 3 calculations (5 objs/19.7 Kb common; 1 calls/chunk) ...
Master: [57.3 secs 0.1% CPU]; Worker: [avg NA% CPU, max 0 bytes]
[[1]]
[1] 2

[[2]]
[1] 4

[[3]]
[1] 6

However, there is error message in the log file:
...
2024-01-30 09:59:21.912408 | event at: 2024-01-30 09:59:21
2024-01-30 09:59:21.916689 | shutting down
Error in qsys$cleanup() : argument "success" is missing, with no default
Calls: <Anonymous> -> <Anonymous>
Execution halted
 
I think there is some issue in the code so that the success code has not been returned properly.  Q() function can still return the results but it failed when I tried to run the same code using targets:

tar_make_clustermq(workers = 2)
...
Error in try(self$worker_list$finalize()) : attempt to apply non-function
In addition: Warning messages:
1: 'self$worker_list$set_common_data' is deprecated.
Use 'env' instead.
See help("Deprecated") 
2: 'self$worker_list$receive_data' is deprecated.
Use 'recv' instead.
See help("Deprecated") 
3: 'function (expr, env = list(), ref = substitute(expr)) 
{
    .Deprecated("send")
    pcall = quote(substitute(expr))
    do.call(self$send, c(list(cmd = eval(pcall)), env))
}' is deprecated.
Use 'send' instead.
See help("Deprecated") 
4: 'self$worker_list$receive_data' is deprecated.
Use 'recv' instead.
See help("Deprecated") 
5: 'function (expr, env = list(), ref = substitute(expr)) 
{
    .Deprecated("send")
    pcall = quote(substitute(expr))
    do.call(self$send, c(list(cmd = eval(pcall)), env))
}' is deprecated.
Use 'send' instead.
See help("Deprecated") 
6: 'self$worker_list$receive_data' is deprecated.
Use 'recv' instead.
See help("Deprecated") 
▶ end pipeline [1.184 minutes]
Error:
! Error running targets::tar_make_clustermq()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: Unexpected worker disconnect

It seems the error is due to the same issue about the "success" status in the clean up of the completed slurm jobs.

I think there should be an easy fix there to ensure the completed jobs with a default success status code.

Thanks,

Wei Zhi

**Comment by mschubert** [comment]
Are you using an older version of targets?

The deprecation warnings happened with the API transition to 0.9.0, but were already addressed by @wlandau. This likely explains the error you are getting as well.

For the SSH scheduler this may indeed be a minor bug, but it's harmless.

**Comment by weizhu365** [comment]
Many thanks for your reply.  The problem got fixed.  Best,

Wei
