### ISSUE TITLE
Make `multicore` work on Windows

### ISSUE THREAD

**Issue by mschubert** [mschubert/clustermq#64]
likely creating a separate R session in the background

can get R executable by `file.path(R.home("bin"), "R")`, but how to get PID in `system` call?

probably split `multicore` qsys in `fork` and `process`, where it defers to what is available (otherwise #54 is difficult)

**Comment by bomeara** [comment]
It's possible that https://github.com/nathanvan/parallelsugar (for mclapply to work across cores on Windows) could be useful for ideas.

**Comment by wlandau** [comment]
Multicore workers are launched one by one.

https://github.com/mschubert/clustermq/blob/2bba401f1676f722b95d11f85514bd6b3dabec64/R/qsys_multicore.r#L16-L19

It seems like we could replace `parallel::mcparallel()` with `callr::r_bg()`. What do you think?

**Comment by mschubert** [comment]
@wlandau I'm planning to use this for #142

**Comment by wlandau** [comment]
Nice!

**Comment by mschubert** [comment]
Superseded by #142
