### ISSUE TITLE
Tests occasionally fail

### ISSUE THREAD

**Issue by mschubert** [mschubert/clustermq#73]
A small minority (e.g. 3 of 66) occasionally fail.

These are not always the same, and not always the same number. I have never seen them fail on an actual scheduling system, so maybe the local run is too fast for some ZeroMQ part to start up every time?

Likely the same behavior that CRAN oberved running on some of their platforms (but not all).

In any case this should be fixed.

**Comment by wlandau** [comment]
Could this be related to the ports used by ZeroMQ? I wonder how often those ports are already occupied (a beginner question, I know).

**Comment by mschubert** [comment]
Thank you for your input, but this is most likely *not* (just) a port binding problem.

clustermq is using [`rzmq::bind.socket`](https://rdrr.io/cran/rzmq/man/bind.socket.html) to check if a port is available. If this function returns `FALSE`, it retries until a port is found ([bind_avail.r#L13](https://github.com/mschubert/clustermq/blob/master/R/bind_avail.r#L13)) or raise an error.

**Comment by wlandau** [comment]
For what it's worth, I sometimes see "Interrupted system call" errors with the multicore schedule. Very rarely, though.
