### ISSUE TITLE
Feature Request: PBSPro/Torque support?

### ISSUE THREAD

**Issue by toupeiro** [mschubert/clustermq#76]
Would love to see support for Altair/Torque spins of PBS for this tool!

**Comment by mschubert** [comment]
Can you try `SGE` with the following template:

```r
#!/bin/bash
#PBS -N {{ job_name }}
#PBS -l nodes={{ n_jobs }}:ppn=1,walltime={{ walltime | 30:00 }}
#PBS -o {{ log_file | /dev/null }}
#PBS -j oe

ulimit -v $(( 1024 * {{ memory | 4096 }} ))
R --no-save --no-restore -e 'clustermq:::worker(\"{{ master }}\")'
```

and tell me if that works for `PBS/Torque`?

**Comment by mschubert** [comment]
@toupeiro I've also added experimental `PBS` support and template for `clustermq.scheduler="pbs"`.

Would be great if you can test this!

```r
devtools::install_github("mschubert/clustermq", ref="develop")
```

**Comment by toupeiro** [comment]
Sorry for the late response I was out of town. I will give this a shot
tomorrow!  Thanks!

**Comment by toupeiro** [comment]
Sorry this took me so long, I finally got a chance to work on this some.
Here is what I've got so far:

In R:

options(+ clustermq.scheduler = "PBS",+ clustermq.template =
"/data/rstudio_projects/shared/acu/templates/r_pbs_template.tmpl"+ )


where my r_template.tmpl looks like (modified just a bit to compensate for
PBS pro differences versus torque

#!/bin/bash
#PBS -N {{ job_name }}
#PBS -l select=1:ncpus=16
#PBS -o {{ log_file | /dev/null }}
#PBS -j oe
#PBS -q datascience
ulimit -v $(( 1024 * {{ memory | 4096 }} ))
R --no-save --no-restore -e 'clustermq:::worker(\"{{ master }}\")'

I've tried a few examples from the vignettes and I get a pretty consistent
error:

> fx = function(x) x * 2 + y> Q(fx, x=1:3, export=list(y=10), n_jobs=1)Submitting 1 worker jobs (ID: 6317) ...Error: is.list(x) is not TRUE

>

**Comment by toupeiro** [comment]
Heres a simple working template I can launch with PBSPro's qsub that bring
me back an interactive R shell:

#PBS -N DSJOB_${USER}
#PBS -l select=1:ncpus=16
#PBS -l walltime=1:00:00
#PBS -q datascience
#PBS -M toupeiro@gmail.com
#PBS -o /data/$PBS_JOBID_$PBS_JOBNAME.out
#PBS -j oe
module load Anaconda
R

**Comment by toupeiro** [comment]
fx = function(x) x * 2 + y> Q(fx, x=1:3, export=list(y=10), n_jobs=1,
log_worker = "TRUE")Submitting 1 worker jobs (ID: 7693) ...Error:
is.list(x) is not TRUE


This is using scheduler = SGE.  It does't appear to actually write a log
anywhere in the working directory

**Comment by mschubert** [comment]
I *think* I found the reason for the `is.list` error on `options(clustermq.scheduler="PBS")`: it is derived from the SGE scheduler, which defines its own setup method, but PBS doesn't know about this. This is due to be fixed in #77 (pt. 1).

However, I don't see how this can happen when you use `options(clustermq.scheduler="SGE")`, because then the right setup method will be called (unless you did not reload the package or restart R and it still uses the PBS scheduler class)

What is the output of:

```r
library(clustermq)
getOption("clustermq.scheduler") # this should output "SGE"
getOption("clustermq.template.sge") # this should point to your _PBS_ template file
w = workers(1, qsys_id="SGE", reuse=FALSE)
```
?

**Comment by mschubert** [comment]
Good to hear it works! :+1:

**Comment by mschubert** [comment]
Setup explained here now: https://github.com/mschubert/clustermq/blob/master/README.md#schedulers
