### ISSUE TITLE
Can not set `job_name` using `template` argument to `Q`

### ISSUE THREAD

**Issue by wlandau** [mschubert/clustermq#89]
On SGE, when I submitted `Q(f, x = 1:2, template = list(job_name = "job")` the `qstat` showed the job name as "cmq6501". Am I using the `template` argument correctly? Is `template` meant to modify the entries in the template file (`options(clustermq.template = "template_file")`)?

**Comment by mschubert** [comment]
Yes, the `template` argument overrides template default values.

However, it will be ignored for variables that the `QSys` requires to function:

* `n_jobs` is how many jobs we submit (as a required argument of `Q`)
* `master` is the master's ZeroMQ address (which the worker requires to connect to)
* `job_name` is used to identify the job (and kill it at the end if it is not cleaned up properly)

Job identifiers could in theory also use the actual IDs instead of assigned names, but these are more difficult to query (needs to parse the output of `qsub`).

**Comment by mschubert** [comment]
This is a low priority for me, so I will not change this any time soon.

**Comment by wlandau** [comment]
In that case, it does make sense to ignore those (maybe with a warning?) Like most users, I am more likely to try to request the number of cores per job, set memory, etc. On SGE, I usually write something like `#$ -pe smp 2` in the template file. When I tried `clustermq::workers(2, template = list(pe = "smp 2"))`, the workers only had one slot each.

**Comment by mschubert** [comment]
Ok, adding a warning seems reasonable.

Are you sure your template has a `pe` argument that can be filled in?
The default template does not (to keep it simple)

**Comment by wlandau** [comment]
Here is my template file.

```r
# From https://github.com/mschubert/clustermq/wiki/SGE
#$ -N {{ job_name }}               # job name
#$ -t 1-{{ n_jobs }}               # submit jobs as array
#$ -j y                            # combine stdout/error in one file
#$ -o {{ log_file | /dev/null }}   # output file
#$ -cwd                            # use pwd as work dir
#$ -V                              # use environment variable
#$ -pe smp 2                       # request 2 cores per job
module load R
ulimit -v $(( 1024 * {{ memory | 4096 }} ))
R --no-save --no-restore -e 'clustermq:::worker("{{ master }}")'
```

Because of the `#$ -pe smp 2` line, I can submit workers with 2 slots each.

```r
> options(clustermq.scheduler = "sge", clustermq.template = "sge_clustermq.tmpl")
> w <- clustermq::workers(4)
Submitting 4 worker jobs (ID: 6506) ...
> system2("qstat")
job-ID     prior   name       user          state submit/start at     queue    jclass slots ja-task-ID
------------------------------------------------------------------------------------------------------------------------------------------------
  33177525 0.55040 cmq6506    censored      r     07/18/2018 10:11:32 censored            2 1
  33177525 0.55040 cmq6506    censored      r     07/18/2018 10:11:35 censored            2 2
  33177525 0.55040 cmq6506    censored      r     07/18/2018 10:11:35 censored            2 3
  33177525 0.55040 cmq6506    censored      t     07/18/2018 10:11:37 censored            2 4
```

When it comes to the `template` argument of `Q()` and friends, can I only reference fields explicitly given in the template file?

**Comment by wlandau** [comment]
Ah, got it. I need custom variables and [`infuser`](https://github.com/bart6114/infuser) syntax in the template file. I could not use `n_jobs` for this purpose because it is already the number of jobs, but I could define `n_slots` in `sge_clustermq.tmpl`

```r
#$ -pe smp {{ n_slots | 1 }}
```

and then set it in the `template` argument.

```r
options(clustermq.scheduler = "sge", clustermq.template = "sge_clustermq.tmpl")
w <- clustermq::workers(4, template = list(n_slots = 3))
f <- function(x){
  x * 2
}
clustermq::Q(x = 1:4, fun = f, n_jobs = 4, template = list(n_slots = 3))
```

Also, I am curious why you chose [`infuser`](https://github.com/bart6114/infuser) rather than [`glue`](https://github.com/tidyverse/glue). I do not know which is better, [`glue`](https://github.com/tidyverse/glue) just seems to be more widely known.
