### ISSUE TITLE
Multicore workers should not change master's .Random.seed

### ISSUE THREAD

**Issue by wlandau** [mschubert/clustermq#90]
Looking through the code and tests, I am glad to see that `clustermq` values reproducibility with respect to pseudo-randomness. Along those lines, would it be possible to keep `workers()` from modifying the `.Random.seed` of the calling R session?

```r
library(digest)
tmp <- rnorm(1)
digest(.Random.seed)
#> [1] "8f6cbceb3880ed84a3f699cd296605a9"
options(clustermq.scheduler = "multicore")
library(clustermq)
digest(.Random.seed)
#> [1] "8f6cbceb3880ed84a3f699cd296605a9"
w <- workers(2, data = list(seed = .Random.seed))
#> Submitting 2 worker jobs (ID: 7921) ...
digest(.Random.seed)
#> [1] "f2aaa2a70102e8447637854974d48a8e"
```

`drake::make()` tries to preserve `.Random.seed` by building targets inside `withr::with_seed()`. [This unit test](https://github.com/ropensci/drake/blob/e99f96cb63a118ab087508a28645af54094ea852/tests/testthat/test-random.R#L19-L28) succeeds for all parallel backends except the new `make(parallelism = "clustermq_staged")` functionality.

**Comment by mschubert** [comment]
It took me a while to understand the issue here, because I first assumed I inadvertently used `set.seed(...)` in multicore processing, which then ends up changing the seed on the master.

However, a change of `.Random.seed` seems to happen every time we sample from any distribution, e.g. when generating data tokens to identify the `common_data` being set at the master.

I'm happy to be convinced that this is something we should control for, but as it stands I would rather put the responsibility on whichever tool is running `clustermq`.

**Comment by wlandau** [comment]
What role do these tokens play? Could a deterministic `digest()` hash do the job instead? On the other hand, I suppose even then `clustermq` calls `sample()` to select ports.

From the user's side, would it be sufficient to wrap `workers()` and `Q()` with `withr::with_preserve_seed()`, or does `clustermq` have other side effects on the seed?

**Comment by mschubert** [comment]
> What role do these tokens play? Could a deterministic `digest()` hash do the job instead? On the other hand, I suppose even then, `clustermq` calls `sample()` to select ports.

Yes, that's right, port binding is sampling as well.

Tokens are there to identify if the `common_data` set at the worker is the same as is required to evaluate `DO_CHUNK`. They are required if a worker is reused with different sets of data. I could use `digest()`, for this, but decided against it for performance and package dependency. However, if I start allowing multiple compute environments on workers it might make more sense to use `digest` instead.

> From the user's side, would it be sufficient to wrap `workers()` and `Q()` with `withr::with_preserve_seed()`, or does `clustermq` have other side effects on the seed?

Yes, that should be sufficient.

**Comment by wlandau** [comment]
Actually, when I wrap `clustermq` functions in `withr::with_preserve_seed()`, I get "Address already in use" errors. Now, I understand why. I think we really do want the seed to change. Not a problem for `drake`, though, because it has its own way of setting seeds for targets.
