### ISSUE TITLE
Question: cleanup() vs finalize()

### ISSUE THREAD

**Issue by wlandau** [mschubert/clustermq#91]
In your example code in https://github.com/mschubert/clustermq/issues/86#issuecomment-402512794, you have an `on.exit(w$cleanup())` line. The `cleanup()` method does not work for me, but `finalize()` does. What is the difference, and which one should I use?

```r
library(clustermq)
#> * Option 'clustermq.scheduler' not set, defaulting to SGE
#> --- see: https://github.com/mschubert/clustermq/wiki#setting-up-the-scheduler
w <- workers(2)
#> Submitting 2 worker jobs (ID: 7504) ...
w$cleanup()
#> Error in max(sapply(private$worker_stats, function(w) w$mem)) :
#>  invalid 'type' (list) of argument
traceback()
#> 3: self$summary_stats()
#> 2: super$cleanup()
#> 1: w$cleanup()
w$finalize() # Also appears to work with `clean = TRUE`.
#> <censored> has registered the job-array task 33180389.1 for deletion
#> <censored> has registered the job-array task 33180389.2 for deletion
```

**Comment by mschubert** [comment]
`cleanup()` is supposed to be a proper shutdown (telling each worker individually to end its process), while `finalize()` is a kill.

I'd recommend to use `cleanup()` and not touch `finallize()`. `on.exit()` is set automatically for the finalizer. The error on `cleanup()` should be fixed now.
