### ISSUE TITLE
Problems collecting child processes when using the multicore backend alongside mclapply()

### ISSUE THREAD

**Issue by wlandau** [mschubert/clustermq#99]
I see warnings like "In selectChildren(ac[!fin], -1): cannot wait for child 16782 as it does not exist" when I invoke `mclapply()` before cleaning up the workers. In [`drake`](https://github.com/ropensci/drake), I was hoping to be able to use `mclapply()` while `clustermq` workers are still up, but it is not such a loss. Does it have something to do with the way `clustermq` needs to change the `SIGCHLD` handler?

```r
options(clustermq.scheduler = "multicore")
w <- clustermq::workers(8)
out <- clustermq::Q(1:2, fun = function(x) x * 2, workers = w)
parallel::mclapply(1:2, sqrt, mc.cores = 2)
w$cleanup() # Warnings go away if I clean up before calling mclapply().
```

**Comment by mschubert** [comment]
This seems to be independent of `clustermq`:

```r
p = parallel::mcparallel({ Sys.sleep(1) })
# parallel::mccollect(p) # uncomment and warnings go away
parallel::mclapply(1:2, sqrt, mc.cores = 2)
# Warning messages:
# 1: In selectChildren(ac[!fin], -1) :
#   cannot wait for child 18305 as it does not exist
#   (repeats a couple of times...)
```

Related: https://github.com/HenrikBengtsson/future/issues/218#issuecomment-410205508, https://github.com/mschubert/clustermq/issues/92

As far as I can tell, this may be a bug in R which was introduced in `3.5.0` (where CI also started reporting these warnings with no changes to `clustermq`). They do not affect function, so you should be safe to suppress them; or wait for the supposed fix to be merged.

**Comment by wlandau** [comment]
Glad the bug was already discovered elsewhere. I am noticing those same warnings in R 3.5.1, so perhaps I need to wait a couple more versions.
